// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozyffixjfugzlqdscpob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eWZmaXhqZnVnemxxZHNjcG9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzY2OTIsImV4cCI6MjA3MzY1MjY5Mn0.WFK1YBx3mGJn2kd5MQrq-59Jsr_a3D0wz97fQv623Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});